<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('area')->insert([
            ['id_area' => 2, 'descripcion' => 'Area Agricola', 'estado' => 1],
            ['id_area' => 1, 'descripcion' => 'Area Logistica', 'estado' => 1],
            ['id_area' => 3, 'descripcion' => 'Area Avicola', 'estado' => 1],
            ['id_area' => 4, 'descripcion' => 'Area Taller Maestranza', 'estado' => 1],
            ['id_area' => 5, 'descripcion' => 'Area Contable', 'estado' => 1],
            ['id_area' => 6, 'descripcion' => 'Area Gerencia General', 'estado' => 1],
        ]);

        DB::table('nucleo')->insert([
            ['id' => 1, 'nomb_nucleo' => 'Nucleo Ezperanza', 'estado' => 1],
            ['id' => 2, 'nomb_nucleo' => 'Nucleo Zodiaco', 'estado' => 1],
        ]);

        DB::table('tipo_afectacion_igv')->insert([
            [
                'id' => 1,
                'codigo' => '10',
                'nomb_impuesto' => 'Gravado - Operación Onerosa',
                'letra_tributo' => 'S',
                'codigo_tributo' => '1000',
                'nomb_tributo' => 'IVA',
                'tipo_tributo' => 'ABC',
                'porcentaje' => 18,
                'estado' => 1,
            ],
            [
                'id' => 2,
                'codigo' => '20',
                'nomb_impuesto' => 'Exonerado - Operación Onerosa',
                'letra_tributo' => 'E',
                'codigo_tributo' => '9997',
                'nomb_tributo' => 'EXO',
                'tipo_tributo' => 'VAT',
                'porcentaje' => 0,
                'estado' => 1,
            ],
            [
                'id' => 3,
                'codigo' => '30',
                'nomb_impuesto' => 'Inafecto - Operación Onerosa',
                'letra_tributo' => 'O',
                'codigo_tributo' => '9998',
                'nomb_tributo' => 'INA',
                'tipo_tributo' => 'FRE',
                'porcentaje' => 0,
                'estado' => 1,
            ],
        ]);

        DB::table('modulos')->insert([
            ['id' => 1, 'modulo' => 'Tablero', 'padre_id' => '0', 'vista' => 'dashboard', 'icon_menu' => 'fas fa-tachometer-alt', 'orden' => 0],
            ['id' => 2, 'modulo' => 'Inventario', 'padre_id' => '0', 'vista' => '', 'icon_menu' => 'fas fa-warehouse', 'orden' => 1],
            ['id' => 3, 'modulo' => 'Kardex Stock', 'padre_id' => '8', 'vista' => 'producto', 'icon_menu' => 'fas fa-check-circle', 'orden' => 14],
            ['id' => 4, 'modulo' => 'Carga Masiva', 'padre_id' => '2', 'vista' => 'carga_masiva', 'icon_menu' => 'fas fa-check-circle', 'orden' => 5],
            ['id' => 5, 'modulo' => 'Administracion', 'padre_id' => '0', 'vista' => '', 'icon_menu' => 'fas fa-users-cog', 'orden' => 6],
            ['id' => 6, 'modulo' => 'Seguridad', 'padre_id' => '0', 'vista' => '', 'icon_menu' => 'fas fa-user-shield', 'orden' => 8],
            ['id' => 7, 'modulo' => 'Usuarios', 'padre_id' => '6', 'vista' => 'register', 'icon_menu' => 'fas fa-check-circle', 'orden' => 9],
            ['id' => 8, 'modulo' => 'Reportes', 'padre_id' => '0', 'vista' => '', 'icon_menu' => 'fas fa-chart-bar', 'orden' => 13],
            ['id' => 9, 'modulo' => 'Documentos', 'padre_id' => '0', 'vista' => '', 'icon_menu' => 'fas fa-file', 'orden' => 12],
            ['id' => 10, 'modulo' => 'Módulos / Perfiles', 'padre_id' => '6', 'vista' => 'seguridad_modulos_perfiles', 'icon_menu' => 'fas fa-check-circle', 'orden' => 11],
            ['id' => 11, 'modulo' => 'Perfil', 'padre_id' => '6', 'vista' => 'perfil_seguridad', 'icon_menu' => 'fas fa-check-circle', 'orden' => 10],
            ['id' => 12, 'modulo' => 'Reporte Kardex', 'padre_id' => '8', 'vista' => 'Reportes/reportes_kardex_X_producto', 'icon_menu' => 'fas fa-check-circle', 'orden' => 16],
            ['id' => 13, 'modulo' => 'Kardex Totalizado', 'padre_id' => '8', 'vista' => 'Reportes/reportes_kardex_Totalizado', 'icon_menu' => 'fas fa-check-circle', 'orden' => 15],
            ['id' => 14, 'modulo' => 'Kardex X Almacen', 'padre_id' => '8', 'vista' => 'Reportes/reportes_kardex_Almacenes', 'icon_menu' => 'fas fa-check-circle', 'orden' => 17],
            ['id' => 15, 'modulo' => 'Proveedor', 'padre_id' => '5', 'vista' => 'Proveedores/proveedor', 'icon_menu' => 'fas fa-check-circle', 'orden' => 7],
            ['id' => 16, 'modulo' => 'Producto', 'padre_id' => '2', 'vista' => 'ProductoModeloReq/producto_sinubica', 'icon_menu' => 'fas fa-check-circle', 'orden' => 2],
            ['id' => 17, 'modulo' => 'Categoria', 'padre_id' => '2', 'vista' => 'ProductoModeloReq/ExtrasProducto/categoria', 'icon_menu' => 'fas fa-check-circle', 'orden' => 4],
            ['id' => 18, 'modulo' => 'Unidad de Medida', 'padre_id' => '2', 'vista' => 'ProductoModeloReq/ExtrasProducto/unidad_medida', 'icon_menu' => 'fas fa-check-circle', 'orden' => 3],
            ['id' => 19, 'modulo' => 'Empresa', 'padre_id' => '5', 'vista' => 'Empresa/Empresa', 'icon_menu' => 'fas fa-check-circle', 'orden' => 18],
            ['id' => 20, 'modulo' => 'Doc Requerimiento', 'padre_id' => '9', 'vista' => 'Documentos/DocumentosRequerimiento', 'icon_menu' => 'fas fa-check-circle', 'orden' => 18],
            ['id' => 21, 'modulo' => 'Rev Requerimiento', 'padre_id' => '9', 'vista' => 'Documentos/RevicionDocumentosRequerimiento', 'icon_menu' => 'fas fa-check-circle', 'orden' => 19],
            ['id' => 22, 'modulo' => 'Tipo cambio', 'padre_id' => '5', 'vista' => 'TipoCambio/TipoCambio', 'icon_menu' => 'fas fa-check-circle', 'orden' => 20],
            ['id' => 24, 'modulo' => 'Configuracion Api', 'padre_id' => '5', 'vista' => 'Configuraciones/ConfiguracionesRutas', 'icon_menu' => 'fas fa-check-circle', 'orden' => 21],
            ['id' => 25, 'modulo' => 'Doc Ingreso', 'padre_id' => '9', 'vista' => 'Documentos/DocumentoIngreso/DocumentoIngreso', 'icon_menu' => 'fas fa-check-circle', 'orden' => 22],
            ['id' => 27, 'modulo' => 'Doc Salida', 'padre_id' => '9', 'vista' => 'Documentos/DocumentoSalida/DocumentoSalida', 'icon_menu' => 'fas fa-check-circle', 'orden' => 23],
            ['id' => 28, 'modulo' => 'Cajas', 'padre_id' => '0', 'vista' => '', 'icon_menu' => 'fas fa-money-bill-wave', 'orden' => 24],
            ['id' => 29, 'modulo' => 'C/Contable', 'padre_id' => '28', 'vista' => 'Cajas/CajaContable/caja_contable', 'icon_menu' => 'fas fa-check-circle', 'orden' => 25],
            ['id' => 30, 'modulo' => 'C/Chica', 'padre_id' => '28', 'vista' => 'Cajas/CajaChica/caja_chica', 'icon_menu' => 'fas fa-check-circle', 'orden' => 26],
            ['id' => 31, 'modulo' => 'R/CajaChica', 'padre_id' => '8', 'vista' => 'Cajas/CajaChica/reportecajachica', 'icon_menu' => 'fas fa-check-circle', 'orden' => 27],
            ['id' => 32, 'modulo' => 'R/CajaContable', 'padre_id' => '8', 'vista' => 'Cajas/CajaContable/reportecajacontable', 'icon_menu' => 'fas fa-check-circle', 'orden' => 28],
        ]);

        DB::table('perfiles')->insert([
            ['id_perfil' => 1, 'descripcion' => 'Administrador', 'estado' => 1, 'fecha_creacion' => " ", 'fecha_actualizacion' => " "],
            ['id_perfil' => 2, 'descripcion' => 'Productor', 'estado' => 1, 'fecha_creacion' => " ", 'fecha_actualizacion' => " "],
            ['id_perfil' => 3, 'descripcion' => 'Ingeniero', 'estado' => 1, 'fecha_creacion' => " ", 'fecha_actualizacion' => " "],
        ]);

        DB::table('almacen')->insert([
            ['id' => 1,'nomb_almacen' => 'Almacen N1','ubic_almacen' => 'Calle Principal, 123','estado' => 1],
            ['id' => 2,'nomb_almacen' => 'Almacen N2','ubic_almacen' => 'Avenida del Sol, 456','estado' => 1],
            ['id' => 3,'nomb_almacen' => 'Almacen N3','ubic_almacen' => 'Calle 8, Barrio Sur','estado' => 1],
            ['id' => 4,'nomb_almacen' => 'Ninguno','ubic_almacen' => '','estado' => 1],
        ]);

        DB::table('comprobante_pago')->insert([
            ['id' => 1, 'descripcion' => 'Otros', 'estado' => 1],
            ['id' => 2, 'descripcion' => 'Factura', 'estado' => 1],
            ['id' => 3, 'descripcion' => 'Boleta de Venta', 'estado' => 1],
            ['id' => 4, 'descripcion' => 'Nota de crédito', 'estado' => 1],
            ['id' => 5, 'descripcion' => 'Nota de débito', 'estado' => 1],
            ['id' => 6, 'descripcion' => 'Guía de remisión - Remitente', 'estado' => 1],
            ['id' => 7, 'descripcion' => 'Ticket o cinta emitido por máquina registradora', 'estado' => 1],
            ['id' => 8, 'descripcion' => 'Guía de Remisión - Transportista', 'estado' => 1],
        ]);



        DB::table('usuarios')->insert([
            [
                'id_usuario' => 1,
                'nomb_usuarios' => 'Cesar Augusto',
                'apellidos_usuarios' => 'Virhuez Robles',
                'dni' => '12444555',
                'usuario' => 'CesarVirhuez',
                'clave' => '$2y$12$gnQLAH5QVfpBLfvQFt.4qeMigLhZoWctXw5j21ln9hU6izn5L0AKW',
                'id_perfil_usuario' => 1,
                'id_Area_usuario' => 6,
                'id_almacen_usuario' => 1,
                'estado' => 1,
            ],
        ]);

        DB::table('config_rutas')->insert([
            ['id' => 1,'api_url' => 'https://dniruc.apisperu.com/api/v1/ruc','api_token' => 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFyaXNlc2NycEBnbWFpbC5jb20ifQ.xE8AVDAGBNR7j1DSr56rUXbjJzhy7oXo59qdjAL_wLY','UsuarioModificar' => 1],
            ['id' => 2,'api_url' => 'https://api.apis.net.pe/v2/sbs/tipo-cambio','api_token' => 'apis-token-11661.mg6ob2gQLMRkvYPVeZwr78glq7eCZDlr','UsuarioModificar' => 1],
        ]);

        DB::table('codigoacceso')->insert([
            ['id' => 1, 'CodigoAcceso' => '12345678', 'UsuarioModificar' => 1],
        ]);

        DB::table('categorias_movimientos')->insert([
            ['id' => 1, 'nombre' => 'DEPOSITO EN CUENTA', 'descripcion' => 'Transferencia directa de fondos a una cuenta bancaria.'],
            ['id' => 2, 'nombre' => 'GIRO', 'descripcion' => 'Orden de pago emitida para transferir dinero a un beneficiario.'],
            ['id' => 3, 'nombre' => 'TRANSFERENCIA DE FONDOS', 'descripcion' => 'Movimiento de dinero entre cuentas bancarias.'],
            ['id' => 4, 'nombre' => 'ORDEN DE PAGO', 'descripcion' => 'Instrucción para realizar un pago específico a un beneficiario.'],
            ['id' => 5, 'nombre' => 'TARJETA DE DEBITO', 'descripcion' => 'Pago mediante tarjeta con cargo directo a una cuenta bancaria.'],
            ['id' => 6, 'nombre' => 'TARJETA DE CREDITO', 'descripcion' => 'Pago mediante tarjeta con crédito otorgado por una entidad financiera.'],
            ['id' => 7, 'nombre' => 'CHEQUES CON LA CLAUSULA NO NEGOCIABLE', 'descripcion' => 'Cheque que no puede ser transferido a un tercero.'],
            ['id' => 8, 'nombre' => 'EFECTIVO, POR OPERACIONES EN LA QUE NO EXISTE OBLIGACION', 'descripcion' => 'Pago en efectivo sin obligaciones contractuales previas.'],
            ['id' => 9, 'nombre' => 'EFECTIVO, EN LOS DEMAS CASOS', 'descripcion' => 'Pago en efectivo bajo circunstancias generales.'],
            ['id' => 10, 'nombre' => 'MEDIOS DE PAGO DEL COMERCIO EXTERIOR', 'descripcion' => 'Instrumentos utilizados para pagos internacionales.'],
            ['id' => 11, 'nombre' => 'LETRAS DE CAMBIO', 'descripcion' => 'Documento que obliga al pago de una cantidad en una fecha específica.'],
            ['id' => 101, 'nombre' => 'TRANSFERENCIAS - COMERCIO EXTERIOR', 'descripcion' => 'Transferencia de dinero relacionada con transacciones internacionales.'],
            ['id' => 102, 'nombre' => 'CHEQUES BANCARIOS - COMERCIO EXTERIOR', 'descripcion' => 'Cheque emitido para transacciones en comercio exterior.'],
            ['id' => 103, 'nombre' => 'ORDEN DE PAGO SIMPLE - COMERCIO EXTERIOR', 'descripcion' => 'Pago emitido para operaciones comerciales internacionales.'],
            ['id' => 104, 'nombre' => 'ORDEN DE PAGO DOCUMENTARIO - COMERCIO EXTERIOR', 'descripcion' => 'Instrucción de pago respaldada por documentos comerciales.'],
            ['id' => 105, 'nombre' => 'REMESA SIMPLE - COMERCIO EXTERIOR', 'descripcion' => 'Transferencia de fondos sin documentos adicionales.'],
            ['id' => 106, 'nombre' => 'REMESA DOCUMENTARIA - COMERCIO EXTERIOR', 'descripcion' => 'Transferencia internacional con presentación de documentos comerciales.'],
            ['id' => 107, 'nombre' => 'CARTA DE CREDITO SIMPLE - COMERCIO EXTERIOR', 'descripcion' => 'Instrumento financiero para garantizar pagos internacionales.'],
            ['id' => 108, 'nombre' => 'CARTA DE CREDITO DOCUMENTARIO - COMERCIO EXTERIOR', 'descripcion' => 'Garantía de pago respaldada por documentos en operaciones internacionales.'],
            ['id' => 999, 'nombre' => 'OTROS MEDIOS DE PAGO (ESPECIFICAR)', 'descripcion' => 'Medios de pago no especificados, detallados por el usuario.'],
        ]);


        DB::table('perfil_modulo')->insert([
            ['idperfil_modulo' => 1, 'id_perfil' => 1, 'id_modulo' => 1, 'vista_inicio' => 1, 'estado' => 1], // Tablero
            ['idperfil_modulo' => 6, 'id_perfil' => 1, 'id_modulo' => 6, 'vista_inicio' => 0, 'estado' => 1], // Seguridad
            ['idperfil_modulo' => 7, 'id_perfil' => 1, 'id_modulo' => 7, 'vista_inicio' => 0, 'estado' => 1], // Usuarios
            
            ['idperfil_modulo' => 10, 'id_perfil' => 1, 'id_modulo' => 10, 'vista_inicio' => 0, 'estado' => 1], // Módulos / Perfiles
            ['idperfil_modulo' => 11, 'id_perfil' => 1, 'id_modulo' => 11, 'vista_inicio' => 0, 'estado' => 1], // Perfil
            
        ]);

        DB::table('tipo_operaciones')->insert([
            ['id' => 1, 'descripcion' => 'VENTA NACIONAL', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 2, 'descripcion' => 'COMPRA NACIONAL', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 3, 'descripcion' => 'CONSIGNACIÓN RECIBIDA', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 4, 'descripcion' => 'CONSIGNACIÓN ENTREGADA', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 5, 'descripcion' => 'DEVOLUCIÓN RECIBIDA', 'tipo' => 'DEVOLUCIÓN', 'estado' => 1],
            ['id' => 6, 'descripcion' => 'DEVOLUCIÓN ENTREGADA', 'tipo' => 'DEVOLUCIÓN', 'estado' => 1],
            ['id' => 7, 'descripcion' => 'BONIFICACIÓN', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 8, 'descripcion' => 'PREMIO', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 9, 'descripcion' => 'DONACIÓN', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 10, 'descripcion' => 'SALIDA A PRODUCCIÓN', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 11, 'descripcion' => 'SALIDA POR TRANSFERENCIA ENTRE ALMACENES', 'tipo' => 'DEVOLUCIÓN', 'estado' => 1],
            ['id' => 12, 'descripcion' => 'RETIRO', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 13, 'descripcion' => 'MERMAS', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 14, 'descripcion' => 'DESMEDROS', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 15, 'descripcion' => 'DESTRUCCIÓN', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 16, 'descripcion' => 'SALDO INICIAL', 'tipo' => 'SALDO INICIAL', 'estado' => 1],
            ['id' => 17, 'descripcion' => 'EXPORTACIÓN', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 18, 'descripcion' => 'IMPORTACIÓN', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 19, 'descripcion' => 'ENTRADA DE PRODUCCIÓN', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 20, 'descripcion' => 'ENTRADA POR DEVOLUCIÓN DE PRODUCCIÓN', 'tipo' => 'DEVOLUCIÓN', 'estado' => 1],
            ['id' => 22, 'descripcion' => 'ENTRADA POR IDENTIFICACIÓN ERRONEA', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 23, 'descripcion' => 'SALIDA POR IDENTIFICACIÓN ERRONEA', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 24, 'descripcion' => 'ENTRADA POR DEVOLUCIÓN DEL CLIENTE', 'tipo' => 'DEVOLUCIÓN', 'estado' => 1],
            ['id' => 25, 'descripcion' => 'SALIDA POR DEVOLUCIÓN AL PROVEEDOR', 'tipo' => 'DEVOLUCIÓN', 'estado' => 1],
            ['id' => 26, 'descripcion' => 'ENTRADA PARA SERVICIO DE PRODUCCIÓN', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 27, 'descripcion' => 'SALIDA POR SERVICIO DE PRODUCCIÓN', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 28, 'descripcion' => 'AJUSTE POR DIFERENCIA DE INVENTARIO', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 29, 'descripcion' => 'ENTRADA DE BIENES EN PRÉSTAMO', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 30, 'descripcion' => 'SALIDA DE BIENES EN PRÉSTAMO', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 31, 'descripcion' => 'ENTRADA DE BIENES EN CUSTODIA', 'tipo' => 'ENTRADA', 'estado' => 1],
            ['id' => 32, 'descripcion' => 'SALIDA DE BIENES EN CUSTODIA', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 33, 'descripcion' => 'MUESTRAS MÉDICAS', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 34, 'descripcion' => 'PUBLICIDAD', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 35, 'descripcion' => 'GASTOS DE REPRESENTACIÓN', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 36, 'descripcion' => 'RETIRO PARA ENTREGA A TRABAJADORES', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 37, 'descripcion' => 'RETIRO POR CONVENIO COLECTIVO', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 38, 'descripcion' => 'RETIRO POR SUSTITUCIÓN DE BIEN SINIESTRADO', 'tipo' => 'SALIDA', 'estado' => 1],
            ['id' => 39, 'descripcion' => 'TRANSFERENCIA ENTRE ALMACEN', 'tipo' => 'DEVOLUCIÓN', 'estado' => 1],
            ['id' => 40, 'descripcion' => 'NINGUNO', 'tipo' => 'NINGUNO', 'estado' => 1],
            ['id' => 41, 'descripcion' => 'OTROS', 'tipo' => 'NINGUNO', 'estado' => 1],
        ]);


        DB::table('centro_costo')->insert([
            ['id' => 1, 'Codigo' => 'VIR.1.G1', 'nomb_centroCos' => 'VIRGO G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 2, 'Codigo' => 'VIR.1.G2', 'nomb_centroCos' => 'VIRGO G2', 'nucleo' => 2, 'estado' => 1],
            ['id' => 3, 'Codigo' => 'VIR.1.G3', 'nomb_centroCos' => 'VIRGO G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 4, 'Codigo' => 'VIR.1.G4', 'nomb_centroCos' => 'VIRGO G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 5, 'Codigo' => 'VIR.1.G5', 'nomb_centroCos' => 'VIRGO G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 6, 'Codigo' => 'VIR.1.G6', 'nomb_centroCos' => 'VIRGO G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 7, 'Codigo' => 'VIR.1.G7', 'nomb_centroCos' => 'VIRGO G7', 'nucleo' => 2, 'estado' => 1],
            ['id' => 8, 'Codigo' => 'CAN.1.G1', 'nomb_centroCos' => 'CANCER G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 9, 'Codigo' => 'CAN.1.G2', 'nomb_centroCos' => 'CANCER G2', 'nucleo' => 2, 'estado' => 1],
            ['id' => 10, 'Codigo' => 'CAN.1.G3', 'nomb_centroCos' => 'CANCER G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 11, 'Codigo' => 'CAN.1.G4', 'nomb_centroCos' => 'CANCER G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 12, 'Codigo' => 'CAN.1.G5', 'nomb_centroCos' => 'CANCER G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 13, 'Codigo' => 'CAN.1.G6', 'nomb_centroCos' => 'CANCER G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 14, 'Codigo' => 'GEM.1.G1', 'nomb_centroCos' => 'GEMINIS G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 15, 'Codigo' => 'GEM.1.G2', 'nomb_centroCos' => 'GEMINIS G2', 'nucleo' => 2, 'estado' => 1],
            ['id' => 16, 'Codigo' => 'GEM.1.G3', 'nomb_centroCos' => 'GEMINIS G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 17, 'Codigo' => 'GEM.1.G4', 'nomb_centroCos' => 'GEMINIS G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 18, 'Codigo' => 'GEM.1.G5', 'nomb_centroCos' => 'GEMINIS G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 19, 'Codigo' => 'GEM.1.G6', 'nomb_centroCos' => 'GEMINIS G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 20, 'Codigo' => 'LEO.1.G1', 'nomb_centroCos' => 'LEO G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 21, 'codigo' => 'LEO.1.G2', 'nomb_centroCos' => 'LEO G2', 'nucleo' => 2, 'estado' => 1],
            ['id' => 22, 'codigo' => 'LEO.1.G3', 'nomb_centroCos' => 'LEO G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 23, 'codigo' => 'LEO.1.G4', 'nomb_centroCos' => 'LEO G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 24, 'codigo' => 'LEO.1.G5', 'nomb_centroCos' => 'LEO G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 25, 'codigo' => 'LEO.1.G6', 'nomb_centroCos' => 'LEO G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 26, 'codigo' => 'LEO.1.G7', 'nomb_centroCos' => 'LEO G7', 'nucleo' => 2, 'estado' => 1],
            ['id' => 27, 'codigo' => 'LEO.1.G8', 'nomb_centroCos' => 'LEO G8', 'nucleo' => 2, 'estado' => 1],
            ['id' => 28, 'codigo' => 'LEO.1.G9', 'nomb_centroCos' => 'LEO G9', 'nucleo' => 2, 'estado' => 1],
            ['id' => 29, 'codigo' => 'LEO.1.G10', 'nomb_centroCos' => 'LEO G10', 'nucleo' => 2, 'estado' => 1],
            ['id' => 30, 'codigo' => 'ARI.1.G1', 'nomb_centroCos' => 'ARIES G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 31, 'codigo' => 'ARI.1.G2', 'nomb_centroCos' => 'ARIES G2', 'nucleo' => 2, 'estado' => 1],
            ['id' => 32, 'codigo' => 'ARI.1.G3', 'nomb_centroCos' => 'ARIES G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 33, 'codigo' => 'ARI.1.G4', 'nomb_centroCos' => 'ARIES G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 34, 'codigo' => 'ARI.1.G5', 'nomb_centroCos' => 'ARIES G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 35, 'codigo' => 'ARI.1.G6', 'nomb_centroCos' => 'ARIES G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 36, 'codigo' => 'ARI.1.G7', 'nomb_centroCos' => 'ARIES G7', 'nucleo' => 2, 'estado' => 1],
            ['id' => 37, 'codigo' => 'ARI.1.G8', 'nomb_centroCos' => 'ARIES G8', 'nucleo' => 2, 'estado' => 1],
            ['id' => 38, 'codigo' => 'ARI.1.G9', 'nomb_centroCos' => 'ARIES G9', 'nucleo' => 2, 'estado' => 1],
            ['id' => 39, 'codigo' => 'ARI.1.G10', 'nomb_centroCos' => 'ARIES G10', 'nucleo' => 2, 'estado' => 1],
            ['id' => 40, 'codigo' => 'TAU.1.G1', 'nomb_centroCos' => 'TAURO G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 41, 'codigo' => 'TAU.1.G2', 'nomb_centroCos' => 'TAURO G2', 'nucleo' => 2, 'estado' => 1],
            ["id" => 42, 'codigo' => "TAU.1.G3", "nomb_centroCos" => "TAURO G3", 'nucleo' => 2, 'estado' => 1],
            ["id" => 43, 'codigo' => "TAU.1.G4", "nomb_centroCos" => "TAURO G4", 'nucleo' => 2, 'estado' => 1],
            ["id" => 44, 'codigo' => "TAU.1.G5", "nomb_centroCos" => "TAURO G5", 'nucleo' => 2, 'estado' => 1],
            ["id" => 45, 'codigo' => "TAU.1.G6", "nomb_centroCos" => "TAURO G6", 'nucleo' => 2, 'estado' => 1],
            ["id" => 46, 'codigo' => "TAU.1.G7", "nomb_centroCos" => "TAURO G7", 'nucleo' => 2, 'estado' => 1],
            ["id" => 47, 'codigo' => "TAU.1.G8", "nomb_centroCos" => "TAURO G8", 'nucleo' => 2, 'estado' => 1],
            ["id" => 48, 'codigo' => "TAU.1.G9", "nomb_centroCos" => "TAURO G9", 'nucleo' => 2, 'estado' => 1],
            ["id" => 49, 'codigo' => "TAU.1.G10", "nomb_centroCos" => "TAURO G10", 'nucleo' => 2, 'estado' => 1],
            ["id" => 50, 'codigo' => "SAG.0.G1", "nomb_centroCos" => "SAGITARIO G1", 'nucleo' => 2, 'estado' => 1],
            ["id" => 51, 'codigo' => "SAG.0.G2", "nomb_centroCos" => "SAGITARIO G2", 'nucleo' => 2, 'estado' => 1],
            ["id" => 52, 'codigo' => "SAG.0.G3", "nomb_centroCos" => "SAGITARIO G3", 'nucleo' => 2, 'estado' => 1],
            ["id" => 53, 'codigo' => "SAG.0.G4", "nomb_centroCos" => "SAGITARIO G4", 'nucleo' => 2, 'estado' => 1],
            ["id" => 54, 'codigo' => "SAG.0.G5", "nomb_centroCos" => "SAGITARIO G5", 'nucleo' => 2, 'estado' => 1],
            ["id" => 55, 'codigo' => "SAG.0.G6", "nomb_centroCos" => "SAGITARIO G6", 'nucleo' => 2, 'estado' => 1],
            ["id" => 56, 'codigo' => "SAG.0.G7", "nomb_centroCos" => "SAGITARIO G7", 'nucleo' => 2, 'estado' => 1],
            ["id" => 57, 'codigo' => "SAG.0.G8", "nomb_centroCos" => "SAGITARIO G8", 'nucleo' => 2, 'estado' => 1],
            ["id" => 58, 'codigo' => "SAG.0.G9", "nomb_centroCos" => "SAGITARIO G9", 'nucleo' => 2, 'estado' => 1],
            ["id" => 59, 'codigo' => "SAG.0.G10", "nomb_centroCos" => "SAGITARIO G10", 'nucleo' => 2, 'estado' => 1],
            ["id" => 60, 'codigo' => "CAP.1.G1", "nomb_centroCos" => "CAPRICORNIO G1", 'nucleo' => 2, 'estado' => 1],
            ["id" => 61, 'codigo' => "CAP.1.G2", "nomb_centroCos" => "CAPRICORNIO G2", 'nucleo' => 2, 'estado' => 1],
            ["id" => 62, 'codigo' => "CAP.1.G3", "nomb_centroCos" => "CAPRICORNIO G3", 'nucleo' => 2, 'estado' => 1],
            ["id" => 63, 'codigo' => "CAP.1.G4", "nomb_centroCos" => "CAPRICORNIO G4", 'nucleo' => 2, 'estado' => 1],
            ["id" => 64, 'codigo' => "CAP.1.G5", "nomb_centroCos" => "CAPRICORNIO G5", 'nucleo' => 2, 'estado' => 1],
            ["id" => 65, 'codigo' => "CAP.1.G6", "nomb_centroCos" => "CAPRICORNIO G6", 'nucleo' => 2, 'estado' => 1],
            ["id" => 66, 'codigo' => "CAP.1.G7", "nomb_centroCos" => "CAPRICORNIO G7", 'nucleo' => 2, 'estado' => 1],
            ["id" => 67, 'codigo' => "CAP.1.G8", "nomb_centroCos" => "CAPRICORNIO G8", 'nucleo' => 2, 'estado' => 1],
            ["id" => 68, 'codigo' => "CAP.1.G9", "nomb_centroCos" => "CAPRICORNIO G9", 'nucleo' => 2, 'estado' => 1],
            ["id" => 69, 'codigo' => "CAP.1.G10", "nomb_centroCos" => "CAPRICORNIO G10", 'nucleo' => 2, 'estado' => 1],
            ["id" => 70, 'codigo' => "LIB.1.G1", "nomb_centroCos" => "LIBRA G1", 'nucleo' => 2, 'estado' => 1],
            ["id" => 71, 'codigo' => "LIB.1.G2", "nomb_centroCos" => "LIBRA G2", 'nucleo' => 2, 'estado' => 1],
            ["id" => 72, 'codigo' => "LIB.1.G3", "nomb_centroCos" => "LIBRA G3", 'nucleo' => 2, 'estado' => 1],
            ["id" => 73, 'codigo' => "LIB.1.G4", "nomb_centroCos" => "LIBRA G4", 'nucleo' => 2, 'estado' => 1],
            ["id" => 74, 'codigo' => "LIB.1.G5", "nomb_centroCos" => "LIBRA G5", 'nucleo' => 2, 'estado' => 1],
            ["id" => 75, 'codigo' => "LIB.1.G6", "nomb_centroCos" => "LIBRA G6", 'nucleo' => 2, 'estado' => 1],
            ["id" => 76, 'codigo' => "LIB.1.G7", "nomb_centroCos" => "LIBRA G7", 'nucleo' => 2, 'estado' => 1],
            ["id" => 77, 'codigo' => "LIB.1.G8", "nomb_centroCos" => "LIBRA G8", 'nucleo' => 2, 'estado' => 1],
            ["id" => 78, 'codigo' => "LIB.1.G9", "nomb_centroCos" => "LIBRA G9", 'nucleo' => 2, 'estado' => 1],
            ["id" => 79, 'codigo' => "LIB.1.G10", "nomb_centroCos" => "LIBRA G10", 'nucleo' => 2, 'estado' => 1],
            ["id" => 80, 'codigo' => "ESC.1.G1", "nomb_centroCos" => "ESCORPIO G1", 'nucleo' => 2, 'estado' => 1],
            ["id" => 81, 'codigo' => "ESC.1.G2", "nomb_centroCos" => "ESCORPIO G2", 'nucleo' => 2, 'estado' => 1],
            ['id' => 82, 'codigo' => 'ESC.1.G3', 'nomb_centroCos' => 'ESCORPIO G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 83, 'codigo' => 'ESC.1.G4', 'nomb_centroCos' => 'ESCORPIO G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 84, 'codigo' => 'ESC.1.G5', 'nomb_centroCos' => 'ESCORPIO G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 85, 'codigo' => 'ESC.1.G6', 'nomb_centroCos' => 'ESCORPIO G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 86, 'codigo' => 'ESC.1.G7', 'nomb_centroCos' => 'ESCORPIO G7', 'nucleo' => 2, 'estado' => 1],
            ['id' => 87, 'codigo' => 'ESC.1.G8', 'nomb_centroCos' => 'ESCORPIO G8', 'nucleo' => 2, 'estado' => 1],
            ['id' => 88, 'codigo' => 'ESC.1.G9', 'nomb_centroCos' => 'ESCORPIO G9', 'nucleo' => 2, 'estado' => 1],
            ['id' => 89, 'codigo' => 'ESC.1.G10', 'nomb_centroCos' => 'ESCORPIO G10', 'nucleo' => 2, 'estado' => 1],
            ['id' => 90, 'codigo' => 'PIS.1.G1', 'nomb_centroCos' => 'PISCIS G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 91, 'codigo' => 'PIS.1.G2', 'nomb_centroCos' => 'PISCIS G2', 'nucleo' => 2, 'estado' => 1],
            ['id' => 92, 'codigo' => 'PIS.1.G3', 'nomb_centroCos' => 'PISCIS G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 93, 'codigo' => 'PIS.1.G4', 'nomb_centroCos' => 'PISCIS G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 94, 'codigo' => 'PIS.1.G5', 'nomb_centroCos' => 'PISCIS G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 95, 'codigo' => 'PIS.1.G6', 'nomb_centroCos' => 'PISCIS G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 96, 'codigo' => 'PIS.1.G7', 'nomb_centroCos' => 'PISCIS G7', 'nucleo' => 2, 'estado' => 1],
            ['id' => 97, 'codigo' => 'PIS.1.G8', 'nomb_centroCos' => 'PISCIS G8', 'nucleo' => 2, 'estado' => 1],
            ['id' => 98, 'codigo' => 'PIS.1.G9', 'nomb_centroCos' => 'PISCIS G9', 'nucleo' => 2, 'estado' => 1],
            ['id' => 99, 'codigo' => 'PIS.1.G10', 'nomb_centroCos' => 'PISCIS G10', 'nucleo' => 2, 'estado' => 1],
            ['id' => 100, 'codigo' => 'ACU.1.G1', 'nomb_centroCos' => 'ACUARIO 1 G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 101, 'codigo' => 'ACU.1.G2', 'nomb_centroCos' => 'ACUARIO 1 G2', 'nucleo' => 2, 'estado' => 1],
            ['id' => 102, 'codigo' => 'ACU.1.G3', 'nomb_centroCos' => 'ACUARIO 1 G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 103, 'codigo' => 'ACU.1.G4', 'nomb_centroCos' => 'ACUARIO 1 G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 104, 'codigo' => 'ACU.1.G5', 'nomb_centroCos' => 'ACUARIO 1 G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 105, 'codigo' => 'ACU.1.G6', 'nomb_centroCos' => 'ACUARIO 1 G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 106, 'codigo' => 'ACU.1.G7', 'nomb_centroCos' => 'ACUARIO 1 G7', 'nucleo' => 2, 'estado' => 1],
            ['id' => 107, 'codigo' => 'ACU.1.G8', 'nomb_centroCos' => 'ACUARIO 1 G8', 'nucleo' => 2, 'estado' => 1],
            ['id' => 108, 'codigo' => 'ACU.1.G9', 'nomb_centroCos' => 'ACUARIO 1 G9', 'nucleo' => 2, 'estado' => 1],
            ['id' => 109, 'codigo' => 'ACU.2.G1', 'nomb_centroCos' => 'ACUARIO 2 G1', 'nucleo' => 2, 'estado' => 1],
            ['id' => 110, 'codigo' => 'ACU.2.G2', 'nomb_centroCos' => 'ACUARIO 2 G2', 'nucleo' => 2, 'estado' => 1],
            ['id' => 111, 'codigo' => 'ACU.2.G3', 'nomb_centroCos' => 'ACUARIO 2 G3', 'nucleo' => 2, 'estado' => 1],
            ['id' => 112, 'codigo' => 'ACU.2.G4', 'nomb_centroCos' => 'ACUARIO 2 G4', 'nucleo' => 2, 'estado' => 1],
            ['id' => 113, 'codigo' => 'ACU.2.G5', 'nomb_centroCos' => 'ACUARIO 2 G5', 'nucleo' => 2, 'estado' => 1],
            ['id' => 114, 'codigo' => 'ACU.2.G6', 'nomb_centroCos' => 'ACUARIO 2 G6', 'nucleo' => 2, 'estado' => 1],
            ['id' => 115, 'codigo' => 'ACU.2.G7', 'nomb_centroCos' => 'ACUARIO 2 G7', 'nucleo' => 2, 'estado' => 1],
            ['id' => 116, 'codigo' => 'ACU.2.G8', 'nomb_centroCos' => 'ACUARIO 2 G8', 'nucleo' => 2, 'estado' => 1],
            ['id' => 117, 'codigo' => 'ACU.2.G9', 'nomb_centroCos' => 'ACUARIO 2 G9', 'nucleo' => 2, 'estado' => 1],
            ['id' => 118, 'codigo' => 'ACU.2.G10', 'nomb_centroCos' => 'ACUARIO 2 G10', 'nucleo' => 2, 'estado' => 1],
            ['id' => 119, 'codigo' => 'ACU.2.G11', 'nomb_centroCos' => 'ACUARIO 2 G11', 'nucleo' => 2, 'estado' => 1],
            ['id' => 120, 'codigo' => 'CES.1.00', 'nomb_centroCos' => 'CESAR 1', 'nucleo' => 1, 'estado' => 1],
            ['id' => 121, 'codigo' => 'CES.1.G1', 'nomb_centroCos' => 'CESAR 1 G1', 'nucleo' => 1, 'estado' => 1],
            ["id" => 122, "codigo" => "CES.1.G2", "nomb_centroCos" => "CESAR 1 G2", 'nucleo' => 1, "estado" => 1],
            ["id" => 123, "codigo" => "CES.1.G3", "nomb_centroCos" => "CESAR 1 G3", 'nucleo' => 1, "estado" => 1],
            ["id" => 124, "codigo" => "CES.1.G4", "nomb_centroCos" => "CESAR 1 G4", 'nucleo' => 1, "estado" => 1],
            ["id" => 125, "codigo" => "CES.1.G5", "nomb_centroCos" => "CESAR 1 G5", 'nucleo' => 1, "estado" => 1],
            ["id" => 126, "codigo" => "CES.1.G6", "nomb_centroCos" => "CESAR 1 G6", 'nucleo' => 1, "estado" => 1],
            ["id" => 127, "codigo" => "CES.2.G1", "nomb_centroCos" => "CESAR 2 G1", 'nucleo' => 1, "estado" => 1],
            ["id" => 128, "codigo" => "CES.2.G2", "nomb_centroCos" => "CESAR 2 G2", 'nucleo' => 1, "estado" => 1],
            ["id" => 129, "codigo" => "CES.2.G3", "nomb_centroCos" => "CESAR 2 G3", 'nucleo' => 1, "estado" => 1],
            ["id" => 130, "codigo" => "CES.2.G4", "nomb_centroCos" => "CESAR 2 G4", 'nucleo' => 1, "estado" => 1],
            ["id" => 131, "codigo" => "CES.2.G5", "nomb_centroCos" => "CESAR 2 G5", 'nucleo' => 1, "estado" => 1],
            ["id" => 132, "codigo" => "CES.2.G6", "nomb_centroCos" => "CESAR 2 G6", 'nucleo' => 1, "estado" => 1],
            ["id" => 133, "codigo" => "CES.2.G7", "nomb_centroCos" => "CESAR 2 G7", 'nucleo' => 1, "estado" => 1],
            ["id" => 134, "codigo" => "CES.2.G8", "nomb_centroCos" => "CESAR 2 G8", 'nucleo' => 1, "estado" => 1],
            ["id" => 135, "codigo" => "CES.2.G9", "nomb_centroCos" => "CESAR 2 G9", 'nucleo' => 1, "estado" => 1],
            ["id" => 136, "codigo" => "CES.2.G10", "nomb_centroCos" => "CESAR 2 G10", 'nucleo' => 1, "estado" => 1],
            ["id" => 137, "codigo" => "GAV.1.G1", "nomb_centroCos" => "GAVILAN G1", 'nucleo' => 1, "estado" => 1],
            ["id" => 138, "codigo" => "GAV.1.G2", "nomb_centroCos" => "GAVILAN G2", 'nucleo' => 1, "estado" => 1],
            ["id" => 139, "codigo" => "GAV.1.G3", "nomb_centroCos" => "GAVILAN G3", 'nucleo' => 1, "estado" => 1],
            ["id" => 140, "codigo" => "GAV.1.G4", "nomb_centroCos" => "GAVILAN G4", 'nucleo' => 1, "estado" => 1],
            ["id" => 141, "codigo" => "GAV.1.G5", "nomb_centroCos" => "GAVILAN G5", 'nucleo' => 1, "estado" => 1],
            ["id" => 142, "codigo" => "GAV.1.G6", "nomb_centroCos" => "GAVILAN G6", 'nucleo' => 1, "estado" => 1],
            ["id" => 143, "codigo" => "GAV.1.G7", "nomb_centroCos" => "GAVILAN G7", 'nucleo' => 1, "estado" => 1],
            ["id" => 144, "codigo" => "GAV.1.G8", "nomb_centroCos" => "GAVILAN G8", 'nucleo' => 1, "estado" => 1],
            ["id" => 145, "codigo" => "GAV.1.G9", "nomb_centroCos" => "GAVILAN G9", 'nucleo' => 1, "estado" => 1],
            ["id" => 146, "codigo" => "GAV.1.G10", "nomb_centroCos" => "GAVILAN G10", 'nucleo' => 1, "estado" => 1],
            ["id" => 147, "codigo" => "CIE.1.G1", "nomb_centroCos" => "CIELO 1 G1", 'nucleo' => 1, "estado" => 1],
            ["id" => 148, "codigo" => "CIE.1.G2", "nomb_centroCos" => "CIELO 1 G2", 'nucleo' => 1, "estado" => 1],
            ["id" => 149, "codigo" => "CIE.1.G3", "nomb_centroCos" => "CIELO 1 G3", 'nucleo' => 1, "estado" => 1],
            ["id" => 150, "codigo" => "CIE.1.G4", "nomb_centroCos" => "CIELO 1 G4", 'nucleo' => 1, "estado" => 1],
            ["id" => 151, "codigo" => "CIE.1.G5", "nomb_centroCos" => "CIELO 1 G5", 'nucleo' => 1, "estado" => 1],
            ["id" => 152, "codigo" => "CIE.1.G6", "nomb_centroCos" => "CIELO 1 G6", 'nucleo' => 1, "estado" => 1],
            ["id" => 153, "codigo" => "CIE.1.G7", "nomb_centroCos" => "CIELO 1 G7", 'nucleo' => 1, "estado" => 1],
            ["id" => 154, "codigo" => "CIE.1.G8", "nomb_centroCos" => "CIELO 1 G8", 'nucleo' => 1, "estado" => 1],
            ["id" => 155, "codigo" => "CIE.1.G9", "nomb_centroCos" => "CIELO 1 G9", 'nucleo' => 1, "estado" => 1],
            ["id" => 156, "codigo" => "CIE.1.G10", "nomb_centroCos" => "CIELO 1 G10", 'nucleo' => 1, "estado" => 1],
            ["id" => 157, "codigo" => "CIE.2.G1", "nomb_centroCos" => "CIELO 2 G1", 'nucleo' => 1, "estado" => 1],
            ["id" => 158, "codigo" => "CIE.2.G2", "nomb_centroCos" => "CIELO 2 G2", 'nucleo' => 1, "estado" => 1],
            ["id" => 159, "codigo" => "CIE.2.G3", "nomb_centroCos" => "CIELO 2 G3", 'nucleo' => 1, "estado" => 1],
            ["id" => 160, "codigo" => "CIE.2.G4", "nomb_centroCos" => "CIELO 2 G4", 'nucleo' => 1, "estado" => 1],
            ['id' => 161, 'codigo' => 'CIE.2.G5', 'nomb_centroCos' => 'CIELO 2 G5', 'nucleo' => 1, 'estado' => 1],
            ['id' => 162, 'codigo' => 'CIE.2.G6', 'nomb_centroCos' => 'CIELO 2 G6', 'nucleo' => 1, 'estado' => 1],
            ['id' => 163, 'codigo' => 'CIE.2.G7', 'nomb_centroCos' => 'CIELO 2 G7', 'nucleo' => 1, 'estado' => 1],
            ['id' => 164, 'codigo' => 'CIE.2.G8', 'nomb_centroCos' => 'CIELO 2 G8', 'nucleo' => 1, 'estado' => 1],
            ['id' => 165, 'codigo' => 'CIE.2.G9', 'nomb_centroCos' => 'CIELO 2 G9', 'nucleo' => 1, 'estado' => 1],
            ['id' => 166, 'codigo' => 'CIE.2.G10', 'nomb_centroCos' => 'CIELO 2 G10', 'nucleo' => 1, 'estado' => 1],
            ['id' => 167, 'codigo' => 'CIE.3.G1', 'nomb_centroCos' => 'CIELO 3 G1', 'nucleo' => 1, 'estado' => 1],
            ['id' => 168, 'codigo' => 'CIE.3.G2', 'nomb_centroCos' => 'CIELO 3 G2', 'nucleo' => 1, 'estado' => 1],
            ['id' => 169, 'codigo' => 'CIE.3.G3', 'nomb_centroCos' => 'CIELO 3 G3', 'nucleo' => 1, 'estado' => 1],
            ['id' => 170, 'codigo' => 'CIE.3.G4', 'nomb_centroCos' => 'CIELO 3 G4', 'nucleo' => 1, 'estado' => 1],
            ['id' => 171, 'codigo' => 'CIE.3.G5', 'nomb_centroCos' => 'CIELO 3 G5', 'nucleo' => 1, 'estado' => 1],
            ['id' => 172, 'codigo' => 'CIE.3.G6', 'nomb_centroCos' => 'CIELO 3 G6', 'nucleo' => 1, 'estado' => 1],
            ['id' => 173, 'codigo' => 'CIE.3.G7', 'nomb_centroCos' => 'CIELO 3 G7', 'nucleo' => 1, 'estado' => 1],
            ['id' => 174, 'codigo' => 'CIE.3.G8', 'nomb_centroCos' => 'CIELO 3 G8', 'nucleo' => 1, 'estado' => 1],
            ['id' => 175, 'codigo' => 'CIE.3.G9', 'nomb_centroCos' => 'CIELO 3 G9', 'nucleo' => 1, 'estado' => 1],
            ['id' => 176, 'codigo' => 'CIE.3.G10', 'nomb_centroCos' => 'CIELO 3 G10', 'nucleo' => 1, 'estado' => 1],
            ['id' => 177, 'codigo' => 'CIE.4.G1', 'nomb_centroCos' => 'CIELO 4 G1', 'nucleo' => 1, 'estado' => 1],
            ['id' => 178, 'codigo' => 'CIE.4.G2', 'nomb_centroCos' => 'CIELO 4 G2', 'nucleo' => 1, 'estado' => 1],
            ['id' => 179, 'codigo' => 'CIE.4.G3', 'nomb_centroCos' => 'CIELO 4 G3', 'nucleo' => 1, 'estado' => 1],
            ['id' => 180, 'codigo' => 'CIE.4.G4', 'nomb_centroCos' => 'CIELO 4 G4', 'nucleo' => 1, 'estado' => 1],
            ['id' => 181, 'codigo' => 'CIE.4.G5', 'nomb_centroCos' => 'CIELO 4 G5', 'nucleo' => 1, 'estado' => 1],
            ['id' => 182, 'codigo' => 'CIE.4.G6', 'nomb_centroCos' => 'CIELO 4 G6', 'nucleo' => 1, 'estado' => 1],
            ['id' => 183, 'codigo' => 'CIE.4.G7', 'nomb_centroCos' => 'CIELO 4 G7', 'nucleo' => 1, 'estado' => 1],
            ['id' => 184, 'codigo' => 'CIE.4.G8', 'nomb_centroCos' => 'CIELO 4 G8', 'nucleo' => 1, 'estado' => 1],
            ['id' => 185, 'codigo' => 'CIE.4.G9', 'nomb_centroCos' => 'CIELO 4 G9', 'nucleo' => 1, 'estado' => 1],
            ['id' => 186, 'codigo' => 'CIE.4.G10', 'nomb_centroCos' => 'CIELO 4 G10', 'nucleo' => 1, 'estado' => 1],
            ['id' => 187, 'codigo' => 'CIE.5.G1', 'nomb_centroCos' => 'CIELO 5 G1', 'nucleo' => 1, 'estado' => 1],
            ['id' => 188, 'codigo' => 'CIE.5.G2', 'nomb_centroCos' => 'CIELO 5 G2', 'nucleo' => 1, 'estado' => 1],
            ['id' => 189, 'codigo' => 'CIE.5.G3', 'nomb_centroCos' => 'CIELO 5 G3', 'nucleo' => 1, 'estado' => 1],
            ['id' => 190, 'codigo' => 'CIE.5.G4', 'nomb_centroCos' => 'CIELO 5 G4', 'nucleo' => 1, 'estado' => 1],
            ['id' => 191, 'codigo' => 'CIE.5.G5', 'nomb_centroCos' => 'CIELO 5 G5', 'nucleo' => 1, 'estado' => 1],
            ['id' => 192, 'codigo' => 'CIE.5.G6', 'nomb_centroCos' => 'CIELO 5 G6', 'nucleo' => 1, 'estado' => 1],
            ['id' => 193, 'codigo' => 'CIE.5.G7', 'nomb_centroCos' => 'CIELO 5 G7', 'nucleo' => 1, 'estado' => 1],
            ['id' => 194, 'codigo' => 'CIE.5.G8', 'nomb_centroCos' => 'CIELO 5 G8', 'nucleo' => 1, 'estado' => 1],
            ['id' => 195, 'codigo' => 'CIE.5.G9', 'nomb_centroCos' => 'CIELO 5 G9', 'nucleo' => 1, 'estado' => 1],
            ['id' => 196, 'codigo' => 'CIE.5.G10', 'nomb_centroCos' => 'CIELO 5 G10', 'nucleo' => 1, 'estado' => 1],
            ['id' => 197, 'codigo' => 'CIE.6.G1', 'nomb_centroCos' => 'CIELO 6 G1', 'nucleo' => 1, 'estado' => 1],
            ['id' => 198, 'codigo' => 'CIE.6.G2', 'nomb_centroCos' => 'CIELO 6 G2', 'nucleo' => 1, 'estado' => 1],
            ['id' => 199, 'codigo' => 'CIE.6.G3', 'nomb_centroCos' => 'CIELO 6 G3', 'nucleo' => 1, 'estado' => 1],
            ["id" => 200, "codigo" => "CIE.6.G4", "nomb_centroCos" => "CIELO 6 G4", 'nucleo' => 1, "estado" => 1],
            ["id" => 201, "codigo" => "CIE.6.G5", "nomb_centroCos" => "CIELO 6 G5", 'nucleo' => 1, "estado" => 1],
            ["id" => 202, "codigo" => "CIE.6.G6", "nomb_centroCos" => "CIELO 6 G6", 'nucleo' => 1, "estado" => 1],
            ["id" => 203, "codigo" => "CIE.6.G7", "nomb_centroCos" => "CIELO 6 G7", 'nucleo' => 1, "estado" => 1],
            ["id" => 204, "codigo" => "CIE.6.G8", "nomb_centroCos" => "CIELO 6 G8", 'nucleo' => 1, "estado" => 1],
            ["id" => 205, "codigo" => "CIE.6.G9", "nomb_centroCos" => "CIELO 6 G9", 'nucleo' => 1, "estado" => 1],
            ["id" => 206, "codigo" => "CIE.6.G10", "nomb_centroCos" => "CIELO 6 G10", 'nucleo' => 1, "estado" => 1],
            ["id" => 207, "codigo" => "CIE.7.G1", "nomb_centroCos" => "CIELO 7 G1", 'nucleo' => 1, "estado" => 1],
            ["id" => 208, "codigo" => "CIE.7.G2", "nomb_centroCos" => "CIELO 7 G2", 'nucleo' => 1, "estado" => 1],
            ["id" => 209, "codigo" => "CIE.7.G3", "nomb_centroCos" => "CIELO 7 G3", 'nucleo' => 1, "estado" => 1],
            ["id" => 210, "codigo" => "CIE.7.G4", "nomb_centroCos" => "CIELO 7 G4", 'nucleo' => 1, "estado" => 1],
            ["id" => 211, "codigo" => "CIE.7.G5", "nomb_centroCos" => "CIELO 7 G5", 'nucleo' => 1, "estado" => 1],
            ["id" => 212, "codigo" => "CIE.7.G6", "nomb_centroCos" => "CIELO 7 G6", 'nucleo' => 1, "estado" => 1],
            ["id" => 213, "codigo" => "CIE.7.G7", "nomb_centroCos" => "CIELO 7 G7", 'nucleo' => 1, "estado" => 1],
            ["id" => 214, "codigo" => "CIE.7.G8", "nomb_centroCos" => "CIELO 7 G8", 'nucleo' => 1, "estado" => 1],
            ["id" => 215, "codigo" => "CIE.7.G9", "nomb_centroCos" => "CIELO 7 G9", 'nucleo' => 1, "estado" => 1],
            ["id" => 216, "codigo" => "CIE.7.G10", "nomb_centroCos" => "CIELO 7 G10", 'nucleo' => 1, "estado" => 1],
            ["id" => 217, "codigo" => "ESP.1.G1", "nomb_centroCos" => "ESPERANZA 1 G1", 'nucleo' => 1, "estado" => 1],
            ["id" => 218, "codigo" => "ESP.1.G2", "nomb_centroCos" => "ESPERANZA 1 G2", 'nucleo' => 1, "estado" => 1],
            ["id" => 219, "codigo" => "ESP.1.G3", "nomb_centroCos" => "ESPERANZA 1 G3", 'nucleo' => 1, "estado" => 1],
            ["id" => 220, "codigo" => "ESP.1.G4", "nomb_centroCos" => "ESPERANZA 1 G4", 'nucleo' => 1, "estado" => 1],
            ["id" => 221, "codigo" => "ESP.1.G5", "nomb_centroCos" => "ESPERANZA 1 G5", 'nucleo' => 1, "estado" => 1],
            ["id" => 222, "codigo" => "ESP.1.G6", "nomb_centroCos" => "ESPERANZA 1 G6", 'nucleo' => 1, "estado" => 1],
            ["id" => 223, "codigo" => "ESP.1.G7", "nomb_centroCos" => "ESPERANZA 1 G7", 'nucleo' => 1, "estado" => 1],
            ["id" => 224, "codigo" => "ESP.1.G8", "nomb_centroCos" => "ESPERANZA 1 G8", 'nucleo' => 1, "estado" => 1],
            ["id" => 225, "codigo" => "ESP.1.G9", "nomb_centroCos" => "ESPERANZA 1 G9", 'nucleo' => 1, "estado" => 1],
            ["id" => 226, "codigo" => "ESP.1.G10", "nomb_centroCos" => "ESPERANZA 1 G10", 'nucleo' => 1, "estado" => 1],
            ["id" => 227, "codigo" => "ESP.2.G1", "nomb_centroCos" => "ESPERANZA 2 G1", 'nucleo' => 1, "estado" => 1],
            ["id" => 228, "codigo" => "ESP.2.G2", "nomb_centroCos" => "ESPERANZA 2 G2", 'nucleo' => 1, "estado" => 1],
            ["id" => 229, "codigo" => "ESP.2.G3", "nomb_centroCos" => "ESPERANZA 2 G3", 'nucleo' => 1, "estado" => 1],
            ["id" => 230, "codigo" => "ESP.2.G4", "nomb_centroCos" => "ESPERANZA 2 G4", 'nucleo' => 1, "estado" => 1],
            ["id" => 231, "codigo" => "ESP.2.G5", "nomb_centroCos" => "ESPERANZA 2 G5", 'nucleo' => 1, "estado" => 1],
            ["id" => 232, "codigo" => "ESP.2.G6", "nomb_centroCos" => "ESPERANZA 2 G6", 'nucleo' => 1, "estado" => 1],
            ["id" => 233, "codigo" => "ESP.2.G7", "nomb_centroCos" => "ESPERANZA 2 G7", 'nucleo' => 1, "estado" => 1],
            ["id" => 234, "codigo" => "ESP.2.G8", "nomb_centroCos" => "ESPERANZA 2 G8", 'nucleo' => 1, "estado" => 1],
            ["id" => 235, "codigo" => "ESP.2.G9", "nomb_centroCos" => "ESPERANZA 2 G9", 'nucleo' => 1, "estado" => 1],
            ["id" => 236, "codigo" => "ESP.2.G10", "nomb_centroCos" => "ESPERANZA 2 G10", 'nucleo' => 1, "estado" => 1],
            ["id" => 237, "codigo" => "N/A", "nomb_centroCos" => "Ninguno", "nucleo" => 1, 'estado' => 1],
        ]);


    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {

    }
};
